### ISSUE TITLE
timecode

### ISSUE THREAD

**Issue by mrnormal** [rockwood/fcpx-Marker-Converter#1]
Seconds doesn't match perfectly.
http://dl.dropbox.com/u/16544740/marker_eric.png
My project is in 25p with no compound clip.
But I must allready thank you cause your script help me a lot as it is !

**Comment by rockwood** [comment]
Are they still off when you import them into compressor? 

I found that compressor has a slight error when importing markers. If I create a text file with a single marker at 01:00:00:00, compressor will actually put it at something like 00:59:57:00. I calibrated the app to account for that error, but it may be that your system doen't have the error.

**Comment by mrnormal** [comment]
I've got the same time code in Compressor Preview and in the .txt file.

Perhaps you can create 2 version (with or without calibration ?)

Another thing, I have no suffix (.txt) after converting .fcpxml (witch was in the previous version)
So I put it in the file name cause Compressor didn't want to load it without.

**Comment by rockwood** [comment]
I just pushed a new release that asks if you want to use error calibration. Let me know if that doesn't fix it.

**Comment by mrnormal** [comment]
Yes, work like a charm both for timecode and doctype.
(I choose no time correction for a 3 our project.)
I own you one : you smooth my workflow !

Last the issue with miltiplicated markers but it's really no big deal to handly edit the .txt file.
I can close the issue, all problems are solved (and a new nice icon in my dock ! :)

Thank you very much !

**Comment by rockwood** [comment]
Glad to hear it! The issue with duplicate markers happens when you split or move a clip after markers have already been made. Until I figure out how to deal with that, I recommend creating markers as the final step in your workflow.
