### ISSUE TITLE
Does not work with 10.3.1?

### ISSUE THREAD

**Issue by hexeric** [rockwood/fcpx-Marker-Converter#5]
Whenever I try to feed your app an XML out of FCPX 10.3.1 (no matter if v1.5 or v1.6) I get an AppleScript error after selecting the output for the TXT file. I'm on El Capitan, any insight or fix?

Details: An error of type -1407 has occurred. (-1407)

**Comment by rockwood** [comment]
@hexeric Thanks for the heads up. I'm not actively using this app at the moment, but I'll try to take a look at the problem when time permits.
